<?php

namespace ContainerHlkaYus;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Nt05JhyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Nt05Jhy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Nt05Jhy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
        ], [
            'em' => '?',
            'requestStack' => '?',
        ]);
    }
}
