<?php

namespace ContainerHlkaYus;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChangeLangueControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ChangeLangueController' shared autowired service.
     *
     * @return \App\Controller\ChangeLangueController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ChangeLangueController.php';

        $container->services['App\\Controller\\ChangeLangueController'] = $instance = new \App\Controller\ChangeLangueController(($container->services['router'] ?? $container->getRouterService()));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ChangeLangueController', $container));

        return $instance;
    }
}
