<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYQxxnbe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYQxxnbe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYQxxnbe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYQxxnbe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYQxxnbe\App_KernelDevDebugContainer([
    'container.build_hash' => 'YQxxnbe',
    'container.build_id' => '638567d4',
    'container.build_time' => 1703552294,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYQxxnbe');
