<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHlkaYus\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHlkaYus/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHlkaYus.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHlkaYus\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHlkaYus\App_KernelDevDebugContainer([
    'container.build_hash' => 'HlkaYus',
    'container.build_id' => '3a2c19af',
    'container.build_time' => 1703703175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHlkaYus');
