<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/vendors-node_modules_fortawesome_fontawesome-free_js_brands_js-node_modules_fortawesome_fonta-afd215.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/app.css',
            ],
        ],
        'langues' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_jquery_dist_jquery_js.js',
                '/build/langues.js',
            ],
        ],
        'theme' => [
            'js' => [
                '/build/runtime.js',
                '/build/theme.js',
            ],
        ],
    ],
],

]];
